### PR TITLE
Removing method info and doing some re-arranging

### PR DESCRIPTION
**Pull request by Gekctek**

### CODE REVIEW

**Comment by Gekctek** [comment]
Still need to figure out the best abstraction for getting all the routes

**Comment by Gekctek** [comment]
Sorry for the delay, i just moved within the last few days and Im still dealing with that. I might be able to get to this later this week/weekend

**Comment by Gekctek** [comment]
@2m0nd try out https://www.nuget.org/packages/EdjCase.JsonRpc.Router/5.0.0-beta.2 and use the IRpcMethodProvider

**Comment by 2m0nd** [comment]
Cool! Thank you

**Comment by Gekctek** [comment]
https://www.nuget.org/packages/EdjCase.JsonRpc.Router.Swagger/1.0.0-beta.1
https://www.nuget.org/packages/EdjCase.JsonRpc.Router/5.0.0-beta.2
Try this out

**Pull request merged**
