### PR TITLE
fix: changed JsonRpcSwaggerProvider from scoped to singleton

### PR DESCRIPTION
**Pull request by CLTanuki**
IDocumentProvider implementation in the ASP requires ISwaggerProvider to be injected as singleton

### CODE REVIEW

**Comment by CLTanuki** [comment]
image
Proof of

**Review by Gekctek — APPROVED** [review]

**Comment by CLTanuki** [comment]
@Gekctek , that'd be great, if You would be so kind to publish these changes for .net 5.0 users.
Thanks.

**Comment by Gekctek** [comment]
https://www.nuget.org/packages/EdjCase.JsonRpc.Router.Swagger/1.0.0-beta.2

Im going to change to .net5 here soon but there shouldnt be a need to upgrade unless there are features that are needed. netstandard2.1 should be usable by .net 5

**Comment by CLTanuki** [comment]
But with asp .net core > 5 my fix is mandatory. Otherwise there is an error 
Ok, I'll publish temporary version into local nuget, until You would publish into generic nuget.

**Comment by Gekctek** [comment]
What exactly is needed from .net 5. i didnt see you modify the TargetFramework so it should be fine. Any .net 5 application should be able to reference it

**Comment by CLTanuki** [comment]
I have mistaken. Not .net 5, but asp .net core 5.

**Comment by Gekctek** [comment]
The Edjcase.JsonRpc.Router.Sample project is asp.net 5 and the `/swagger` route seems to work just fine

**Comment by CLTanuki** [comment]
I have built a small showcase to reproduce.
This is new project scaffolded with `dotnet new web`.
https://github.com/CLTanuki/showcase
Screenshot at 2021-05-18 23-11-58
Screenshot at 2021-05-18 23-12-07


Both Linux and Windows hosts break at the start point.

**Comment by CLTanuki** [comment]
There is some work-around to handle base class:
```csharp
app.UseSwagger();
app.UseSwaggerUI();
app.UseJsonRpcWithBaseController<BaseRpcController>();
```
but it does not matter, since error occurs within AddJsonRpcWithSwagger.

**Pull request merged**
