### PR TITLE
add metadata service

### PR DESCRIPTION
**Pull request by 2m0nd**
To create documentation, need get methods, their parameters and response types.
https://github.com/edjCase/JsonRpc/issues/84

### CODE REVIEW

**Comment by Gekctek** [comment]
What information do you need from this? Just `path -> list of methods`? Im thinking we tweak the IRpcMethodProvider instead also because its doing a similar thing, rather than adding something new

**Comment by Gekctek** [comment]
This has actually pointed out something i have wanted to fix for a while: exposing `MethodInfo`. Im working on something right now

**Comment by 2m0nd** [comment]
I need a list of routes with methods in route. 
In my example metadata service return RouteInfo[].
My example initialize static global context in startup https://github.com/edjCase/JsonRpc/pull/85/files#diff-d2bfe347d2d081acf93698190cd98c58R158 - this code allow access not to metada from not httpContext.

I want implement custom ISwaggerProvider in library Swashbuckle.AspNetCore for documentation my api, when used StaticRpcMethodDataAccessor in JsonRpcMetadata Vaule property is null. If extended implementation of IRpcMethodProvider will be similar behavior with null Value.

**Comment by Gekctek** [comment]
What are you getting out of the .net `MethodInfo` class, im going to be abstracting that out so this is no longer dependent on that

**Comment by Gekctek** [comment]
Will finish it later tonight or tomorrow but ive been working on a different branch called `RemoveMethodInfo`

**Comment by 2m0nd** [comment]
wait https://github.com/edjCase/JsonRpc/pull/86

**Pull request closed without merging**
